name: Docker Build PS4-PKG-Tools

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Update build-linux.sh script for C++23 support
        run: |
          # Making sure build-linux.sh sets C++23 standard
          sed -i 's/cmake -DBUILD_PKG_TOOL=ON/cmake -DBUILD_PKG_TOOL=ON -DCMAKE_CXX_STANDARD=23/g' build-linux.sh
          cat build-linux.sh
      
      - name: Build in Docker
        run: |
          # Using your existing build-linux.sh script with C++23 support
          chmod +x ./build-linux.sh
          ./build-linux.sh
      
      - name: Upload Docker-built artifact
        uses: actions/upload-artifact@v4
        with:
          name: ps4-pkg-tool-linux-docker
          path: linux-build/ps4-pkg-tool