name: Create Release

# Only create releases when code is merged to main branch
on:
  push:
    branches: [ main ]
  # Allow manual triggering from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # This job requires the build jobs to complete first
  create-release:
    name: Create Release
    # Only run after both build jobs have completed successfully
    needs: [build-macos, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        # Extract version from CMakeLists.txt
        run: |
          VERSION=$(grep -oP 'project\(ps4-pkg-tools VERSION \K[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt 2>/dev/null || echo "0.1.0")
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          
      - name: Generate changelog
        id: changelog
        run: |
          # Get commit messages since last tag
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$PREVIOUS_TAG" ]; then
            # If no previous tag, get all commits (limit to last 15)
            CHANGELOG=$(git log -n 15 --pretty=format:"* %h %s ([%an](https://github.com/$( echo $GITHUB_REPOSITORY | cut -d'/' -f1 )/%an))" | sed 's/^/  /')
            COMMIT_RANGE="First 15 commits"
          else
            # Otherwise, get commits since last tag
            CHANGELOG=$(git log ${PREVIOUS_TAG}..HEAD --pretty=format:"* %h %s ([%an](https://github.com/$( echo $GITHUB_REPOSITORY | cut -d'/' -f1 )/%an))" | sed 's/^/  /')
            COMMIT_RANGE="Changes since ${PREVIOUS_TAG}"
          fi
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "**${COMMIT_RANGE}**" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: PS4-PKG-Tools v${{ steps.get_version.outputs.version }}
          body: |
            # PS4-PKG-Tools version ${{ steps.get_version.outputs.version }}
            
            ## Changes
            ${{ steps.changelog.outputs.CHANGELOG }}
            
            ## Binaries
            This release includes binaries for:
            - macOS
            - Linux
            
            ## SHA-256 Checksums
            _Added during asset upload_
          draft: false
          prerelease: false

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: ps4-pkg-tool-macos
          path: ./artifacts/macos

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: ps4-pkg-tool-linux
          path: ./artifacts/linux

      - name: Package macOS binary
        run: |
          cd ./artifacts/macos
          chmod +x ps4-pkg-tool
          zip -r ../../ps4-pkg-tool-macos.zip ps4-pkg-tool
          cd ../..

      - name: Package Linux binary
        run: |
          cd ./artifacts/linux
          chmod +x ps4-pkg-tool
          tar -czvf ../../ps4-pkg-tool-linux.tar.gz ps4-pkg-tool
          cd ../..

      - name: Generate checksums
        run: |
          echo "## SHA-256 Checksums" > checksums.txt
          echo '```' >> checksums.txt
          sha256sum ps4-pkg-tool-macos.zip ps4-pkg-tool-linux.tar.gz >> checksums.txt
          echo '```' >> checksums.txt
          cat checksums.txt

      - name: Upload macOS Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ps4-pkg-tool-macos.zip
          asset_name: ps4-pkg-tool-macos.zip
          asset_content_type: application/zip

      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ps4-pkg-tool-linux.tar.gz
          asset_name: ps4-pkg-tool-linux.tar.gz
          asset_content_type: application/gzip

      - name: Update release body with checksums
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const checksums = fs.readFileSync('checksums.txt', 'utf8');
            
            const { owner, repo } = context.repo;
            const release_id = '${{ steps.create_release.outputs.id }}';
            
            const release = await github.rest.repos.getRelease({
              owner,
              repo,
              release_id
            });
            
            const updatedBody = release.data.body.replace('_Added during asset upload_', checksums);
            
            await github.rest.repos.updateRelease({
              owner,
              repo,
              release_id,
              body: updatedBody
            });

# Include the build jobs from build.yml so that the workflow is self-contained
# This ensures the release job has access to the build artifacts
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - name: Install dependencies
        run: |
          brew install cmake
          # Add other dependencies your project needs
      
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake -DBUILD_PKG_TOOL=ON -DCMAKE_CXX_STANDARD=23 ..
          make -j$(sysctl -n hw.ncpu)
      
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: ps4-pkg-tool-macos
          path: build/ps4-pkg-tool

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev zlib1g-dev
          
          # Install newer CMake version (3.24+)
          wget https://github.com/Kitware/CMake/releases/download/v3.28.3/cmake-3.28.3-linux-x86_64.sh -O cmake-installer.sh
          chmod +x cmake-installer.sh
          sudo mkdir -p /opt/cmake
          sudo ./cmake-installer.sh --skip-license --prefix=/opt/cmake
          sudo ln -sf /opt/cmake/bin/cmake /usr/local/bin/cmake
          cmake --version
          
          # Install a newer gcc/g++ with C++23 support
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc-13 g++-13
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100
          gcc --version
          g++ --version
      
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake -DBUILD_PKG_TOOL=ON -DCMAKE_CXX_STANDARD=23 ..
          make -j$(nproc)
      
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: ps4-pkg-tool-linux
          path: build/ps4-pkg-tool