name: Windows Build PS4-PKG-Tools

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - name: Setup Visual Studio environment
        uses: ilammy/msvc-dev-cmd@v1
      
      - name: Configure CMake
        run: |
          mkdir -Force build
          cd build
          # Use our Windows patch file for CryptoPP compatibility
          cmake -DBUILD_PKG_TOOL=ON -DCMAKE_CXX_STANDARD=23 -DCMAKE_MODULE_PATH="${{ github.workspace }}/.github" -C "${{ github.workspace }}/.github/windows-cryptopp-patch.cmake" ..
      
      - name: Build
        run: |
          cd build
          cmake --build . --config ${{ matrix.configuration }} --parallel
      
      - name: Prepare artifacts
        run: |
          mkdir -Force windows-build
          if ("${{ matrix.configuration }}" -eq "Release") {
            Copy-Item "build\Release\ps4-pkg-tool.exe" -Destination "windows-build\"
          } else {
            Copy-Item "build\Debug\ps4-pkg-tool.exe" -Destination "windows-build\ps4-pkg-tool-debug.exe"
          }
      
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: ps4-pkg-tool-windows-${{ matrix.configuration }}
          path: windows-build/